name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:  
    runs-on: windows-latest 
    - name: Checkout Code  
      uses: actions/checkout@v3 

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x' 

    - name: Set Build Number  
      run: |
        $date = Get-Date -Format "yyyyMMddHHmmss"
        echo "BUILD_NUMBER=$date" | Out-File -FilePath $env:GITHUB_ENV -Append

    - name: Build with Version and Custom DLL Name
      run: dotnet build --configuration Release /p:AssemblyName=PiShockLibrary /p:Version=1.0.$(BuildNumber)
      working-directory: ./PiShockApi
      env:
        BuildNumber: ${{ env.BUILD_NUMBER }}

    - name: Publish with Version and Custom DLL Name
      run: dotnet publish --configuration Release --output ./publish /p:AssemblyName=PiShockLibrary /p:Version=1.0.$(BuildNumber)
      working-directory: ./PiShockApi
      env:
        BuildNumber: ${{ env.BUILD_NUMBER }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: PiShockLibrary
        path: ./PiShockApi/publish/PiShockLibrary.dll
