name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x' 

    - name: List contents of the repository root
      run: ls

    - name: Change to Project Directory
      run: cd PiShockApi

    - name: List contents of the PiShockApi directory
      run: ls

    - name: Build with Version and Custom DLL Name
      run: dotnet build --configuration Release /p:AssemblyName=PiShockLibrary /p:Version=1.0.$(BuildNumber)

    - name: Publish with Version and Custom DLL Name
      run: dotnet publish --configuration Release --output ./publish /p:AssemblyName=PiShockLibrary /p:Version=1.0.$(BuildNumber)

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: PiShockLibrary
        path: ./publish/PiShockLibrary.dll
