name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build_and_publish:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'  
    - name: Set Build Number
      run: |
        $date = Get-Date -Format "yyyyMMddHHmmss"
        echo "BUILD_NUMBER=$date" | Out-File -FilePath $env:GITHUB_ENV -Append
      shell: pwsh

    - name: List contents of the repository root
      run: ls

    - name: Build with Version and Custom DLL Name
      run: |
        dotnet build --configuration Release /p:AssemblyName=PiShockLibrary /p:Version=1.0.0-alpha.$env:BUILD_NUMBER
      working-directory: ./PiShockApi
      shell: pwsh
      env:
        BUILD_NUMBER: ${{ env.BUILD_NUMBER }}

    - name: Publish with Version and Custom DLL Name
      run: |
        dotnet publish --configuration Release --output ./publish /p:AssemblyName=PiShockLibrary /p:Version=1.0.0-alpha.$env:BUILD_NUMBER
      working-directory: ./PiShockApi
      shell: pwsh
      env:
        BUILD_NUMBER: ${{ env.BUILD_NUMBER }}

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.0-alpha.${{ env.BUILD_NUMBER }}
        release_name: Release v1.0.0-alpha.${{ env.BUILD_NUMBER }}
        body: |
          Automated release for version 1.0.0-alpha.${{ env.BUILD_NUMBER }}
        draft: false
        prerelease: true

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./PiShockApi/publish/PiShockLibrary.dll
        asset_name: PiShockLibrary.dll
        asset_content_type: application/octet-stream
